# Generated by Django 5.0.7 on 2025-02-09 01:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='departement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='bookingsystem.departement'),
        ),
        migrations.RemoveField(
            model_name='executivemeeting',
            name='substitute_executive',
        ),
        migrations.AddField(
            model_name='executivemeeting',
            name='substitute_executive',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role__in': ['admin', 'department_chief', 'director', 'executive', 'staff']}, related_name='substituted_meetings', to=settings.AUTH_USER_MODEL),
        ),
    ]
