# Generated by Django 5.0.7 on 2025-02-09 01:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsystem', '0002_alter_booking_departement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='executivemeeting',
            name='participants',
        ),
        migrations.AddField(
            model_name='executivemeeting',
            name='participants_departments',
            field=models.ManyToManyField(blank=True, related_name='meeting_participants', to='bookingsystem.departement'),
        ),
        migrations.AddField(
            model_name='executivemeeting',
            name='participants_users',
            field=models.ManyToManyField(blank=True, related_name='meeting_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
