# Generated by Django 5.0.7 on 2025-02-09 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsystem', '0004_alter_executivemeeting_participants_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='departement',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='bookingsystem.departement', verbose_name='Department'),
            preserve_default=False,
        ),
    ]
