# Generated by Django 5.0.7 on 2025-02-09 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsystem', '0005_customuser_departement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='departement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='bookingsystem.departement', verbose_name='Department'),
        ),
    ]
