# Generated by Django 5.0.7 on 2025-02-09 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsystem', '0006_alter_customuser_departement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executivemeeting',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Execute', 'Execute'), ('Cancelled', 'Cancelled')], max_length=50),
        ),
    ]
