# Generated by Django 5.0.7 on 2025-02-10 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingsystem', '0007_alter_executivemeeting_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='departement',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='bookingsystem.departement', verbose_name='Department'),
            preserve_default=False,
        ),
    ]
